version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=remote_config
      - POSTGRES_PASSWORD=gaCVE26C  # 请修改为强密码
      - POSTGRES_DB=remote_config
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - postgres
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=postgresql://remote_config:gaCVE26C@postgres:5432/remote_config  # 请保持密码一致
      - SECRET_KEY=2b4b648e1061b9a92031072525abcee4b0cd84a2cf378224b6e506ac0e7402f6  # 使用安全密钥
      - ENVIRONMENT=production
      - ALLOWED_HOSTS=*,18.136.104.162
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - CORS_ORIGINS=*

volumes:
  postgres_data: 